---
- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    state: restarted
  listen: Restart systemd-timesyncd

- name: Restart chronyd
  service:
    name: chronyd.service
    state: restarted
  listen: Restart chronyd